---
AWSTemplateFormatVersion: 2010-09-09

Description: Reference Architecture to host Moodle on AWS - Creates S3 artifact bucket

Metadata:

  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: S3 Parameters
      Parameters:
        - S3BucketName
    ParameterLabels:
      S3BucketName:
        default: S3 Bucket Name

Parameters:
  S3BucketName:
    AllowedPattern: ^([a-zA-Z0-9]*)$
    Description: The S3 Bucket name.
    Type: String

Resources:
  S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref S3BucketName